<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('courses')->insert([
            [
                'title' => 'HTML1',
                'description' => 'HTML1説明',
                'outline' => 'HTML1概要HTML1概要HTML1概要HTML1概要HTML1概要HTML1概要',
                'teacher_id' => 1,
                'target' => '初心者',
                'need' => '特になし',
                'thumbnail' => "img/noimage.png",
                'course_url' => 'html1_url',
                'publish_flg' => 1,
                'created_by' => 'html1_author',
                'updated_by' => 'html1_author',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'JavaScript1',
                'description' => 'JavaScript1説明',
                'outline' => 'JavaScript1概要JavaScript1概要JavaScript1概要JavaScript1概要JavaScript1概要JavaScript1概要JavaScript1概要',
                'teacher_id' => 2,
                'target' => '中級者',
                'need' => 'HTML基礎・CSS基礎',
                'thumbnail' => "img/noimage.png",
                'course_url' => 'javascript1_url',
                'publish_flg' => 1,
                'created_by' => 'javascript1_author',
                'updated_by' => 'javascript1_author',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'PHP1',
                'description' => 'PHP1説明',
                'outline' => "PHP1概要PHP1概要PHP1概要PHP1概要\nPHP1概要PHP1概要PHP1概要PHP1概要PHP1概要PHP1概要PHP1概要PHP1概要",
                'teacher_id' => 3,
                'target' => '上級者',
                'need' => 'HTML基礎・CSS基礎・JavaScript基礎',
                'thumbnail' => "img/noimage.png",
                'course_url' => 'php1_url',
                'publish_flg' => 1,
                'created_by' => 'php1_author',
                'updated_by' => 'php1_author',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'HTML2',
                'description' => 'HTML2説明',
                'outline' => 'HTML2概要HTML2概要HTML2概要HTML2概要HTML2概要HTML2概要HTML2概要HTML2概要HTML2概要HTML2概要',
                'teacher_id' => 4,
                'target' => '初心者',
                'need' => 'HTML基礎',
                'thumbnail' => "img/noimage.png",
                'course_url' => 'html2_url',
                'publish_flg' => 1,
                'created_by' => 'html2_author',
                'updated_by' => 'html2_author',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'JavaScript2',
                'description' => 'JavaScript2説明',
                'outline' => 'JavaScript2概要JavaScript2概要JavaScript2概要JavaScript2概要JavaScript2概要JavaScript2概要JavaScript2概要JavaScript2概要',
                'teacher_id' => 5,
                'target' => '中級者',
                'need' => 'HTML基礎・CSS基礎・JavaScript基礎',
                'thumbnail' => "img/noimage.png",
                'course_url' => 'javascript2_url',
                'publish_flg' => 1,
                'created_by' => 'javascript2_author',
                'updated_by' => 'javascript2_author',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'PHP2',
                'description' => 'PHP2説明',
                'outline' => 'PHP2概要PHP2概要PHP2概要PHP2概要PHP2概要PHP2概要PHP2概要PHP2概要PHP2概要PHP2概要PHP2概要PHP2概要',
                'teacher_id' => 6,
                'target' => '上級者',
                'need' => 'HTML基礎・CSS基礎・JavaScript基礎・PHP基礎',
                'thumbnail' => "img/noimage.png",
                'course_url' => 'php2_url',
                'publish_flg' => 1,
                'created_by' => 'php2_author',
                'updated_by' => 'php2_author',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'CSS',
                'description' => 'CSS説明',
                'outline' => 'CSS概要CSS概要CSS概要CSS概要CSS概要CSS概要CSS概要CSS概要CSS概要',
                'teacher_id' => 7,
                'target' => '初心者',
                'need' => 'HTML基礎',
                'thumbnail' => "img/noimage.png",
                'course_url' => 'css_url',
                'publish_flg' => 1,
                'created_by' => 'css_author',
                'updated_by' => 'css_author',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Vue.js',
                'description' => 'Vue.js説明',
                'outline' => 'Vue.js概要Vue.js概要Vue.js概要Vue.js概要Vue.js概要Vue.js概要Vue.js概要Vue.js概要',
                'teacher_id' => 8,
                'target' => '中級者',
                'need' => 'HTML基礎・CSS基礎・JavaScript基礎',
                'thumbnail' => "img/noimage.png",
                'course_url' => 'vuejs_url',
                'publish_flg' => 1,
                'created_by' => 'vuejs_author',
                'updated_by' => 'vuejs_author',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Laravel',
                'description' => 'Laravel説明',
                'outline' => 'Laravel概要Laravel概要Laravel概要Laravel概要Laravel概要Laravel概要Laravel概要Laravel概要Laravel概要Laravel概要Laravel概要Laravel概要',
                'teacher_id' => 9,
                'target' => '上級者',
                'need' => 'HTML基礎・CSS基礎・JavaScript基礎・PHP基礎',
                'thumbnail' => "img/noimage.png",
                'course_url' => 'laravel_url',
                'publish_flg' => 1,
                'created_by' => 'laravel_author',
                'updated_by' => 'laravel_author',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'TailwindCSS',
                'description' => 'TailwindCSS説明',
                'outline' => 'TailwindCSS概要TailwindCSS概要TailwindCSS概要TailwindCSS概要TailwindCSS概要TailwindCSS概要TailwindCSS概要TailwindCSS概要TailwindCSS概要TailwindCSS概要TailwindCSS概要',
                'teacher_id' => 10,
                'target' => '初心者',
                'need' => 'HTML基礎・CSS基礎・JavaScript基礎・Laravel基礎',
                'thumbnail' => "img/noimage.png",
                'course_url' => 'tailwindcss_url',
                'publish_flg' => 1,
                'created_by' => 'tailwindcss_author',
                'updated_by' => 'tailwindcss_author',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
