<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class TeacherSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('teachers')->insert([
            [
                'last_name' => 'テスト',
                'first_name' => '教師',
                'last_name_en' => 'Test',
                'first_name_en' => 'Teacher',
                'email' => 'test_t@example.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password'),
                'image' => '',
                'profile' => 'aaaaaaaaaa',
                'hp' => 'https://www.aa',
                'x' => 'https://twitter.com/aa',
                'youtube' => 'https://www.youtube.com/@aa',
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'last_name' => 'ああ',
                'first_name' => 'ああ',
                'last_name_en' => 'aa',
                'first_name_en' => 'aa',
                'email' => 'aa_t@example.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('aaaaaaaa'),
                'image' => '',
                'profile' => 'aaaaaaaaaa',
                'hp' => 'https://www.aa',
                'x' => 'https://twitter.com/aa',
                'youtube' => 'https://www.youtube.com/@aa',
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'last_name' => 'いい',
                'first_name' => 'いい',
                'last_name_en' => 'ii',
                'first_name_en' => 'ii',
                'email' => 'ii_t@example.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('iiiiiiii'),
                'image' => '',
                'profile' => 'iiiiiiiiii',
                'hp' => 'https://www.ii',
                'x' => 'https://twitter.com/ii',
                'youtube' => 'https://www.youtube.com/@ii',
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'last_name' => 'うう',
                'first_name' => 'うう',
                'last_name_en' => 'uu',
                'first_name_en' => 'uu',
                'email' => 'uu_t@example.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('uuuuuuuu'),
                'image' => '',
                'profile' => 'uuuuuuuuuu',
                'hp' => 'https://www.uu',
                'x' => 'https://twitter.com/uu',
                'youtube' => 'https://www.youtube.com/@uu',
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'last_name' => 'ええ',
                'first_name' => 'ええ',
                'last_name_en' => 'ee',
                'first_name_en' => 'ee',
                'email' => 'ee_t@example.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('eeeeeeee'),
                'image' => '',
                'profile' => 'eeeeeeeeee',
                'hp' => 'https://www.ee',
                'x' => 'https://twitter.com/ee',
                'youtube' => 'https://www.youtube.com/@ee',
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'last_name' => 'おお',
                'first_name' => 'おお',
                'last_name_en' => 'oo',
                'first_name_en' => 'oo',
                'email' => 'oo_t@example.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('oooooooo'),
                'image' => '',
                'profile' => 'oooooooooo',
                'hp' => 'https://www.oo',
                'x' => 'https://twitter.com/oo',
                'youtube' => 'https://www.youtube.com/@oo',
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'last_name' => 'かか',
                'first_name' => 'かか',
                'last_name_en' => 'kaka',
                'first_name_en' => 'kaka',
                'email' => 'kaka_t@example.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('kakakakakakakaka'),
                'image' => '',
                'profile' => 'kakakakakakakakakaka',
                'hp' => 'https://www.kaka',
                'x' => 'https://twitter.com/kaka',
                'youtube' => 'https://www.youtube.com/@kaka',
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'last_name' => 'きき',
                'first_name' => 'きき',
                'last_name_en' => 'kiki',
                'first_name_en' => 'kiki',
                'email' => 'kiki_t@example.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('kikikikikikikiki'),
                'image' => '',
                'profile' => 'kikikikikikikikikiki',
                'hp' => 'https://www.kiki',
                'x' => 'https://twitter.com/kiki',
                'youtube' => 'https://www.youtube.com/@kiki',
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'last_name' => 'くく',
                'first_name' => 'くく',
                'last_name_en' => 'kuku',
                'first_name_en' => 'kuku',
                'email' => 'kuku_t@example.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('kukukukukukukuku'),
                'image' => '',
                'profile' => 'kukukukukukukukukuku',
                'hp' => 'https://www.kuku',
                'x' => 'https://twitter.com/kuku',
                'youtube' => 'https://www.youtube.com/@kuku',
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'last_name' => 'けけ',
                'first_name' => 'けけ',
                'last_name_en' => 'keke',
                'first_name_en' => 'keke',
                'email' => 'keke_t@example.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('kekekekekekekeke'),
                'image' => '',
                'profile' => 'kekekekekekekekekeke',
                'hp' => 'https://www.keke',
                'x' => 'https://twitter.com/keke',
                'youtube' => 'https://www.youtube.com/@keke',
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'last_name' => 'ここ',
                'first_name' => 'ここ',
                'last_name_en' => 'koko',
                'first_name_en' => 'koko',
                'email' => 'koko_t@example.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('kokokokokokokoko'),
                'image' => '',
                'profile' => 'kokokokokokokokokoko',
                'hp' => 'https://www.koko',
                'x' => 'https://twitter.com/koko',
                'youtube' => 'https://www.youtube.com/@koko',
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
